name: .NET Microservices CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  identity-service:
    name: Identity Service - Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore services/identity-service/IdentityService.sln

      - name: Build
        run: dotnet build services/identity-service/IdentityService.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test services/identity-service/IdentityService.sln --no-build --configuration Release


  account-service:
    name: Account Service - Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore services/account-service/AccountService.sln

      - name: Build
        run: dotnet build services/account-service/AccountService.sln --no-restore --configuration Release


  transaction-service:
    name: Transaction Service - Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore services/transaction-service/TransactionService.sln

      - name: Build
        run: dotnet build services/transaction-service/TransactionService.sln --no-restore --configuration Release
