name: .NET Microservices CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  identity-service-ci:
    name: Identity Service - Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Identity Service
        run: dotnet restore services/identity-service/IdentityService.sln

      - name: Build Identity Service
        run: dotnet build services/identity-service/IdentityService.sln --no-restore --configuration Release

      - name: Test Identity Service
        run: dotnet test services/identity-service/IdentityService.sln --no-build --configuration Release
